task: mnist
lr: 0.001
epochs: 250
batch_size: 256
ckpt: ckpt/ddpm_vae_mnist/
save_interval: 10000
log_interval: 50
log_file: logs/ddpm_vae_mnist/

ddpm:
  feat_dim: [1,28,28]
  temb_dim: 196
  T: 1000
  n_res_blocks: 2

vae:
  T: 1000
  temb_dim: 196
  encoder:
    n_res_blocks: 2
    in_channels: [1, 64,]
    out_channels: [64, 64]
    downsampling_type: 'conv'
    embedding_dim: 1000

  decoder:
    n_res_blocks: 2
    in_channels: [64, 64]
    out_channels: [64, 64]
    upsampling_type: 'interpolate'
    embedding_dim: 1000
    final_channels: 1