model:
  out_dim: 2
  layer_out_dim: 64
  down:
    in_channels:
      - [3, 64]
      - [64, 128]
      - [128, 256]
      - [256, 512]
    out_channels:
      - [64, 64]
      - [128, 128]
      - [256, 256]
      - [512, 512]
  up:
    in_channels:
      - [1024, 512]
      - [512, 256]
      - [256, 128]
      - [128, 64]
    out_channels:
      - [512, 512]
      - [256, 256]
      - [128, 128]
      - [64, 64]
  bottle_neck:
    in_channels: [512, 1024]
    out_channels: [1024, 1024]
